#hikari数据源
spring:
  datasource:
    dynamic:
      primary: backstage
      strict: false
      hikari:
        minimum-idle: 5
        maximum-pool-size: 15
        auto-commit: true
        idle-timeout: 30000
        pool-name: DatebookHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
      datasource:
        backstage:
          url: jdbc:mysql://mysql:3306/backstage?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
          username: root
          password: xuPOYbq50PKD3L76
          driver-class-name: com.mysql.cj.jdbc.Driver
        basic:
          url: jdbc:mysql://mysql:3306/basic?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
          username: root
          password: xuPOYbq50PKD3L76
          driver-class-name: com.mysql.cj.jdbc.Driver

  #redis设置
  redis:
    database: 1
    host: redis
    port: 6379
    password: zBt8hFOJGfga9EQFP
    timeout: 50000
    jedis:
      pool:
        max-active: 100   # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接

  #nacos
  cloud:
    nacos:
      discovery:
        namespace: 4a63fef0-5e44-4e4b-976d-38aa49c5aef0
        server-addr: http://nacos:10000

#输出mybatis sql
logging:
  level:
    com.looedu.mapper: debug