server:
  port: 3101


spring:
  application:
    name: join-event
  cloud:
    loadbalancer:
      retry:
        enabled: true #重试机制开关
  profiles:
    active: '@profileActive@'
  main:        # 设置 为true ,即 允许 同名
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  config: classpath:logback-spring.xml
knife4j:
  enable: true
  openapi:
    title: smart-join-event官方文档
    description: "api文档"
    email: z1aoyu@gmail.com
    concat: 粥粥
    version: v1.0.0
  production: false
  setting:
    custom-code: 500
    enable-footer-custom: false
    language: zh_cn
    enable-footer: true
    enable-debug: true
    enable-open-api: true
    enable-host: false


swagger:
  enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*.xml
  type-aliases-package: com.dynamic.join-event
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


idworker:
  snowflake:
    workerId: 1 #工作机器ID(0~31)




# 线程池配置
threadpoolproperty:
  corePoolSize: 4
  maxPoolSize: 8
  keepAliveSeconds: 60
  queueCapacity: 100
  threadNamePrefix: join-event-ThreadPoolExecutor-
  rejectedExecutionHandler:  1
